# Generated by Django 4.2.15 on 2025-08-31 09:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(blank=None, editable=False, null=True, populate_from='news_title', unique=True),
        ),
    ]
