# Generated by Django 4.2.15 on 2025-08-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_img',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='news_img'),
        ),
    ]
